pacman::p_load(lme4,MuMIn,readxl,dplyr,data.table,ggpubr)

df_NAm  <- read.csv('/vol/milkunB/jbosmans/PV_determinants_NAm/df_PI_NAm.csv')
df_SAm  <- read.csv('/vol/milkunB/jbosmans/PV_determinants_SAm/df_PI_SAm.csv')
df_Eur  <- read.csv('/vol/milkunB/jbosmans/PV_determinants_Eur/df_PI_Eur.csv')
df_Asia <- read.csv('/vol/milkunB/jbosmans/PV_determinants_Asia/df_PI_Asia.csv')

# change 'sign' to characters (somehow gets changed into integer when saving / loading csv)
df_NAm$sign  <- as.character(df_NAm$sign)
df_SAm$sign  <- as.character(df_SAm$sign)
df_Eur$sign  <- as.character(df_Eur$sign)
df_Asia$sign <- as.character(df_Asia$sign)

pdf(file='Plot_predictor_importance.pdf',width=12,height=14)

par(mfrow=c(2,2),mar=c(2,3,1,3),cex=1.4)
par(mar=c(3,7.2,1,3))
barplot(df_NAm$PI,names.arg=df_NAm$predictor,horiz=TRUE,las=1,col=df_NAm$sign,border=df_NAm$sign,xlim=c(0,0.3))
title('North America')
par(mar=c(3,0,1,10.2))
barplot(df_Eur$PI,names.arg=df_Eur$predictor,horiz=TRUE,las=1,col=df_Eur$sign,border=df_Eur$sign,xlim=c(0,0.3),yaxt='n')
title('Europe')
legend("bottomright", inset=.02,c('+','-'), fill=c('#3399FF','#cc3300'),border=c('#3399FF','#cc3300'), cex=1.4,box.lty = 0)
par(mar=c(3,7.2,1,3))
barplot(df_SAm$PI,names.arg=df_SAm$predictor,horiz=TRUE,las=1,col=df_SAm$sign,border=df_SAm$sign,xlim=c(0,0.3))
title('South America')
par(mar=c(3,0,1,10.2))
barplot(df_Asia$PI,names.arg=df_Asia$predictor,horiz=TRUE,las=1,col=df_Asia$sign,border=df_Asia$sign,xlim=c(0,0.3),yaxt='n')
title('Asia')
#legend(x=0.4,y=NULL,legend=c('+','-'),col=c('#3399FF','#cc3300'))
#barplot(df_Asia$PI,names.arg=df_Asia$predictor,horiz=TRUE,las=1,col=df_Asia$sign,border=df_Asia$sign,xlim=c(0,0.55),yaxt='n', annotate("text",x=0.1,y=as.character('Wetland'),label='Asia'))

dev.off()
system('gv Plot_predictor_importance.pdf')
